// GENERATED by tools/stagecut/cut_stage.py tidegate from art/stages/tidegate/masks.json.
// Collision lines measured on the painting, in world pixels. Rerun the script to change.
// Painting 1672x941 scaled by 0.64593 (worldWidth 1080); the main walk line
// measured at painting (852, 617) is world (0, 0).
import type { Platform, Rect } from '../../core/types';

export const TIDEGATE_PLATFORMS: readonly Platform[] = [
  { x: -248, y: 0, w: 496, h: 24, solid: true, ledgeLeft: true, ledgeRight: true }, // main
  { x: -234, y: -84, w: 134, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // left
  { x: 101, y: -84, w: 134, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // right
];

/** The painting's world rect. */
export const TIDEGATE_CAMERA_BOUNDS: Rect = { x: -550, y: -399, w: 1080, h: 608 };

/** Camera bounds grown by 48 left, 48 top, 48 right, 96 bottom. */
export const TIDEGATE_BLAST: Rect = { x: -598, y: -447, w: 1176, h: 752 };
