// GENERATED by tools/stagecut/cut_tidegate.py from art/stages/tidegate/masks.json.
// Collision lines measured on the painting, in world pixels. Rerun the script to change.
import type { Platform } from '../../core/types';

export const TIDEGATE_PLATFORMS: readonly Platform[] = [
  { x: -180, y: 0, w: 360, h: 24, solid: true, ledgeLeft: true, ledgeRight: true }, // main
  { x: -183, y: -84, w: 124, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // left
  { x: 63, y: -84, w: 124, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // right
];
