// GENERATED by tools/stagecut/cut_stage.py moonanchor from art/stages/moonanchor/masks.json.
// Collision lines measured on the painting, in world pixels. Rerun the script to change.
// Painting 1536x1024 scaled by 0.70312 (worldWidth 1080); the main walk line
// measured at painting (764, 697) is world (0, 0).
import type { Platform, Rect } from '../../core/types';

export const MOONANCHOR_PLATFORMS: readonly Platform[] = [
  { x: -246, y: 0, w: 492, h: 24, solid: true, ledgeLeft: true, ledgeRight: true }, // main
  { x: -205, y: -84, w: 120, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // left
  { x: -85, y: -140, w: 165, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // centre
  { x: 91, y: -84, w: 116, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // right
];

/** The painting's world rect. */
export const MOONANCHOR_CAMERA_BOUNDS: Rect = { x: -537, y: -490, w: 1080, h: 720 };

/** Camera bounds grown by 48 left, -50 top, 48 right, 96 bottom. */
export const MOONANCHOR_BLAST: Rect = { x: -585, y: -440, w: 1176, h: 766 };
