export const INPUT_BUFFER = 6;        // frames an input stays buffered
export const SMASH_TAP_WINDOW = 5;    // frames since direction press that turns attack into a smash
export const SMASH_CHARGE_MAX = 60;   // frames
export const SMASH_CHARGE_BONUS = 0.4;  // +40% damage at full charge
export const SHIELD_MAX = 60;
export const SHIELD_DECAY = 0.12;     // per frame held
export const SHIELD_REGEN = 0.07;     // per frame not held
export const SHIELD_BREAK_STUN = 180;
export const SHIELD_STUN_PER_DAMAGE = 0.6;  // frames of shield stun per damage point, +2 floor
export const SPOT_DODGE = { total: 22, invStart: 3, invEnd: 17 };
export const ROLL = { total: 30, invStart: 4, invEnd: 19, distance: 44 };
export const AIR_DODGE = { total: 30, invStart: 3, invEnd: 27 };
export const LEDGE_HANG_INVULN = 40;
export const LEDGE_MAX_REGRABS = 3;
export const RESPAWN_INVULN = 120;
export const RESPAWN_PLATFORM_FRAMES = 180;
export const KB_DECAY = 0.051;        // px/frame of launch speed lost per frame
export const KB_TO_VEL = 0.06;        // launch speed px/frame per knockback unit
export const HITSTUN_PER_KB = 0.4;
export const TUMBLE_KB = 80;          // knockback above which victim tumbles
export const HITLAG = (damage: number) => Math.min(20, Math.floor(damage * 0.5) + 4);
export const SAKURAI_WEAK_ANGLE = 0;
export const SAKURAI_STRONG_ANGLE = 40;
export const SAKURAI_KB_THRESHOLD = 60;
