"""Pack the Aeval sheet crops into two atlases and write the TypeScript tables.

Contract: art/aeval/INTEGRATION_SPEC.md section A. Pure Python 3.12 + Pillow.
Crop pixels are copied as-is; nothing is scaled or redrawn.

    python tools/sheetcut/pack.py
"""
from __future__ import annotations

import base64
import io
import json
import sys
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
CROPS = ROOT / "art" / "aeval" / "sheets" / "crops"
SHEETMAP = ROOT / "art" / "aeval" / "sheetmap.json"
OUT = ROOT / "src" / "characters" / "aeval" / "art"

MAX_W = 2048
GUTTER = 1
MAX_B64 = int(1.5 * 1024 * 1024)


def ordered_unique(names):
    seen: dict[str, None] = {}
    for n in names:
        seen.setdefault(n, None)
    return list(seen)


def shelf_pack(images: dict[str, Image.Image]):
    """Tallest first, left to right, new shelf when the row is full."""
    order = sorted(images, key=lambda n: (-images[n].height, -images[n].width, n))
    widest = max(im.width for im in images.values())
    total_area = sum((im.width + GUTTER) * (im.height + GUTTER) for im in images.values())
    # Aim for a roughly square atlas, never above MAX_W.
    target = max(widest, min(MAX_W, int(total_area ** 0.5 * 1.15) + 1))
    x = y = shelf_h = 0
    used_w = 0
    rects: dict[str, tuple[int, int, int, int]] = {}
    for n in order:
        im = images[n]
        if x > 0 and x + im.width > target:
            y += shelf_h + GUTTER
            x = shelf_h = 0
        rects[n] = (x, y, im.width, im.height)
        used_w = max(used_w, x + im.width)
        x += im.width + GUTTER
        shelf_h = max(shelf_h, im.height)
    height = y + shelf_h
    atlas = Image.new("RGBA", (used_w, height), (0, 0, 0, 0))
    for n, (rx, ry, _, _) in rects.items():
        atlas.paste(images[n], (rx, ry))
    return atlas, rects


def png_b64(im: Image.Image) -> str:
    buf = io.BytesIO()
    im.save(buf, format="PNG", optimize=True)
    return base64.b64encode(buf.getvalue()).decode("ascii")


def write_sheet_ts(path: Path, const: str, origin: str, b64: str, rects, anchors) -> None:
    lines = [
        "// Generated by tools/sheetcut/pack.py. Do not edit.",
        "import type { ImageSheetData } from '../../../core/types';",
        f"export const {const}: ImageSheetData = {{",
        f"  url: 'data:image/png;base64,{b64}',",
        f"  origin: '{origin}',",
        "  frames: {",
    ]
    for n in sorted(rects):
        x, y, w, h = rects[n]
        ax, ay = anchors[n]
        lines.append(f"    '{n}': [{x}, {y}, {w}, {h}, {ax}, {ay}],")
    lines += ["  },", "};", ""]
    path.write_text("\n".join(lines), encoding="utf-8", newline="\n")


def anim_ts(name: str, a: dict, strip: str = "") -> str:
    frames = ", ".join(f"'{f.removeprefix(strip)}'" for f in a["frames"])
    holds = a["holds"]
    fps = round(60 / (sum(holds) / len(holds)))
    parts = [
        f"frames: [{frames}]",
        f"holds: [{', '.join(str(h) for h in holds)}]",
        f"fps: {fps}",
        f"loop: {'true' if a.get('loop') else 'false'}",
    ]
    if a.get("mirror"):
        parts.append("mirror: true")
    return f"  {name}: {{ {', '.join(parts)} }},"


def main() -> int:
    smap = json.loads(SHEETMAP.read_text(encoding="utf-8"))
    manifest = json.loads((CROPS / "manifest.json").read_text(encoding="utf-8"))

    for group in ("body", "fx"):
        for name, a in smap[group].items():
            if len(a["frames"]) != len(a["holds"]):
                print(f"error: {group}.{name} has {len(a['frames'])} frames but {len(a['holds'])} holds")
                return 1

    body_names = ordered_unique(f for a in smap["body"].values() for f in a["frames"])
    fx_names = ordered_unique(f for a in smap["fx"].values() for f in a["frames"])

    missing = [n for n in body_names + fx_names if not (CROPS / f"{n}.png").exists()]
    no_meta = [n for n in body_names if n not in manifest["frames"]]
    no_meta += [n for n in fx_names if n.removeprefix("fx_") not in manifest["fx"]]
    if missing or no_meta:
        for n in missing:
            print(f"missing crop png: {n}.png")
        for n in no_meta:
            print(f"missing manifest entry: {n}")
        return 1

    OUT.mkdir(parents=True, exist_ok=True)
    report = {}
    for group, names, const, origin, fname in (
        ("body", body_names, "AEVAL_BODY_SHEET", "bottom-center", "atlas.body.ts"),
        ("fx", fx_names, "AEVAL_FX_SHEET", "center", "atlas.fx.ts"),
    ):
        images = {n: Image.open(CROPS / f"{n}.png").convert("RGBA") for n in names}
        anchors = {}
        for n, im in images.items():
            meta = manifest["frames"][n] if group == "body" else manifest["fx"][n.removeprefix("fx_")]
            if (meta["w"], meta["h"]) != im.size:
                print(f"error: {n}.png is {im.size}, manifest says {(meta['w'], meta['h'])}")
                return 1
            anchors[n] = (meta["ax"], meta["ay"])
        if group == "fx":
            # Atlas fx frames use the manifest's fx keys (orb0, crescent1, ...):
            # the renderer finds effect frames by probing <sprite>0, <sprite>1, ...
            images = {n.removeprefix("fx_"): im for n, im in images.items()}
            anchors = {n.removeprefix("fx_"): a for n, a in anchors.items()}
        atlas, rects = shelf_pack(images)
        b64 = png_b64(atlas)
        write_sheet_ts(OUT / fname, const, origin, b64, rects, anchors)
        report[group] = (atlas.width, atlas.height, len(b64))
        over = " OVER 1.5 MB LIMIT" if len(b64) > MAX_B64 else ""
        print(f"{group}: {len(names)} frames, atlas {atlas.width}x{atlas.height}, base64 {len(b64)} bytes{over}")

    lines = [
        "// Generated by tools/sheetcut/pack.py from art/aeval/sheetmap.json. Do not edit.",
        "import type { AnimDef, AnimName } from '../../../core/types';",
        "",
        "export const AEVAL_ANIMS: Record<AnimName, AnimDef> = {",
    ]
    lines += [anim_ts(n, a) for n, a in smap["body"].items()]
    lines += ["};", "", "export const AEVAL_FX_ANIMS: Record<string, AnimDef> = {"]
    lines += [anim_ts(n, a, "fx_") for n, a in smap["fx"].items()]
    lines += ["};", ""]
    (OUT / "anims.ts").write_text("\n".join(lines), encoding="utf-8", newline="\n")

    print(json.dumps({"atlas": {k: list(v) for k, v in report.items()}}))
    return 0


if __name__ == "__main__":
    sys.exit(main())
