// GENERATED by tools/stagecut/cut_stage.py hearthmoor from art/stages/hearthmoor/masks.json.
// Collision lines measured on the painting, in world pixels. Rerun the script to change.
// Painting 1672x941 scaled by 0.64593 (worldWidth 1080); the main walk line
// measured at painting (820, 536) is world (0, 0).
import type { Platform, Rect } from '../../core/types';

export const HEARTHMOOR_PLATFORMS: readonly Platform[] = [
  { x: -298, y: 0, w: 596, h: 24, solid: true, ledgeLeft: true, ledgeRight: true }, // main
  { x: -338, y: -84, w: 210, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // left
  { x: 159, y: -84, w: 203, h: 8, solid: false, ledgeLeft: false, ledgeRight: false }, // right
];

/** The painting's world rect. */
export const HEARTHMOOR_CAMERA_BOUNDS: Rect = { x: -530, y: -346, w: 1080, h: 608 };

/** Camera bounds grown by 48 left, 101 top, 48 right, 96 bottom. */
export const HEARTHMOOR_BLAST: Rect = { x: -578, y: -447, w: 1176, h: 805 };
